### ISSUE TITLE
gulp error on Windows

### ISSUE THREAD

**Issue by bermetj** [janczizikow/sleek#30]
Thank you for the theme! Trying to install it on my Win 10 Home machine using WSL and get an error when using gulp. I am new to gulp and sass, so any help would be greatly appreciated. When I serve the site without gulp, it works, but the changes in sass are not populating.

```
$ gulp

assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/mnt/c/Users/berme/Desktop/Site/bermet-info/gulpfile.js:60:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at execute (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/liftoff/index.js:203:12)
    at module.exports (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/liftoff/index.js:195:5)
    at /mnt/c/Users/berme/Desktop/Site/bermet-info/node_modules/liftoff/index.js:165:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleek@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleek@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bermetj** [comment]
Looks like there is an issue with gulp 4 as 
`gulp.task(name, deps, func)` was replaced by `gulp.task(name, gulp.{series|parallel}(deps, func))`
https://fettblog.eu/gulp-4-parallel-and-series/

solved by downgrading gulp to 3
`$ npm install gulp@3.9.1`

This solved the issue
